name: wenflutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
      - images/pic1.jpg
      - images/pic2.jpg
      - images/pic3.jpg
      - images/pic4.jpg
      - images/pavlova.jpg
      - images/pic5.jpg
      - images/pic6.jpg
      - images/pic7.jpg
      - images/pic8.jpg
      - images/img1.jpg
      - images/img2.jpg
      - images/img3.jpg
      - images/img4.jpg
      - images/img5.jpg
      - images/img6.jpg
      - images/img7.jpg
      - images/img8.jpg
      - images/img9.jpg
      - images/img10.jpg
      - images/img11.jpg
      - images/img12.jpg
      - images/img13.jpg
      - images/img14.jpg
      - images/img15.jpg
      - images/img16.jpg
      - images/img17.jpg
      - images/img18.jpg
      - images/img19.jpg
      - images/img20.jpg
      - images/img21.jpg
      - images/img22.jpg
      - images/img23.jpg
      - images/img24.jpg
      - images/img25.jpg
      - images/img26.jpg
      - images/img27.jpg
      - images/img28.jpg
      - images/img29.jpg
      - images/img30.jpg
      - images/pic.jpg
      - images/lake.jpg
      - images/pic0233.jpg
